/// List of Nigerian states and corresponding LGAs
Map<String, List<String>> stateLgaMap = {
  'Abia': [
    'Aba North',
    'Aba South',
    'Arochukwu',
    'Bende',
    'Ikwuano',
    'Isiala Ngwa North',
    'Isiala Ngwa South',
    'Isuikwuato',
    'Obi Ngwa',
    'Ohafia',
    'Osisioma',
    'Ugwunagbo',
    'Ukwa East',
    'Ukwa West',
    'Umuahia North',
    'Umuahia South',
    'Umu Nneochi'
  ],
  'Adamawa': [
    'Demsa',
    'Fufore',
    'Ganye',
    'Gayuk',
    'Gombi',
    'Grie',
    'Hong',
    'Jada',
    'Lamurde',
    'Madagali',
    'Maiha',
    'Mayo-Belwa',
    'Michika',
    'Mubi North',
    'Mubi South',
    'Numan',
    'Shelleng',
    'Song',
    'Toungo',
    'Yola North',
    'Yola South'
  ],
  'Akwa Ibom': [
    'Abak',
    'Eastern Obolo',
    'Eket',
    'Esit-Eket',
    'Essien Udim',
    'Etim-Ekpo',
    'Etinan',
    'Ibeno',
    'Ibesikpo-Asutan',
    'Ibiono-Ibom',
    'Ika',
    'Ikono',
    'Ikot Abasi',
    'Ikot Ekpene',
    'Ini',
    'Itu',
    'Mbo',
    'Mkpat-Enin',
    'Nsit-Atai',
    'Nsit-Ibom',
    'Nsit-Ubium',
    'Obot Akara',
    'Okobo',
    'Onna',
    'Oron',
    'Oruk Anam',
    'Udung-Uko',
    'Ukanafun',
    'Uruan',
    'Urue-Offong/Oruko',
    'Uyo'
  ],
  'Anambra': [
    'Aguata',
    'Anambra East',
    'Anambra West',
    'Anaocha',
    'Awka North',
    'Awka South',
    'Ayamelum',
    'Dunukofia',
    'Ekwusigo',
    'Idemili North',
    'Idemili South',
    'Ihiala',
    'Njikoka',
    'Nnewi North',
    'Nnewi South',
    'Ogbaru',
    'Onitsha North',
    'Onitsha South',
    'Orumba North',
    'Orumba South',
    'Oyi'
  ],
  'Bauchi': [
    'Alkaleri',
    'Bauchi',
    'Bogoro',
    'Damban',
    'Darazo',
    'Dass',
    'Gamawa',
    'Ganjuwa',
    'Giade',
    'Itas/Gadau',
    'Jama\'are',
    'Katagum',
    'Kirfi',
    'Misau',
    'Ningi',
    'Shira',
    'Tafawa Balewa',
    'Toro',
    'Warji',
    'Zaki'
  ],
  'Bayelsa': [
    'Brass',
    'Ekeremor',
    'Kolokuma/Opokuma',
    'Nembe',
    'Ogbia',
    'Sagbama',
    'Southern Ijaw',
    'Yenagoa'
  ],
  'Benue': [
    'Ado',
    'Agatu',
    'Apa',
    'Buruku',
    'Gboko',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Katsina-Ala',
    'Konshisha',
    'Kwande',
    'Logo',
    'Makurdi',
    'Obi',
    'Ogbadibo',
    'Ohimini',
    'Oju',
    'Okpokwu',
    'Otukpo',
    'Tarka',
    'Ukum',
    'Ushongo',
    'Vandeikya'
  ],
  'Borno': [
    'Abadam',
    'Askira/Uba',
    'Bama',
    'Bayo',
    'Biu',
    'Chibok',
    'Damboa',
    'Dikwa',
    'Gubio',
    'Guzamala',
    'Gwoza',
    'Hawul',
    'Jere',
    'Kaga',
    'Kala/Balge',
    'Konduga',
    'Kukawa',
    'Kwaya Kusar',
    'Mafa',
    'Magumeri',
    'Maiduguri',
    'Marte',
    'Mobbar',
    'Monguno',
    'Ngala',
    'Nganzai',
    'Shani'
  ],
  'Cross River': [
    'Abi',
    'Akamkpa',
    'Akpabuyo',
    'Bakassi',
    'Bekwarra',
    'Biase',
    'Boki',
    'Calabar Municipal',
    'Calabar South',
    'Etung',
    'Ikom',
    'Obanliku',
    'Obubra',
    'Obudu',
    'Odukpani',
    'Ogoja',
    'Yakuur',
    'Yala'
  ],
  'Delta': [
    'Aniocha North',
    'Aniocha South',
    'Bomadi',
    'Burutu',
    'Ethiope East',
    'Ethiope West',
    'Ika North East',
    'Ika South',
    'Isoko North',
    'Isoko South',
    'Ndokwa East',
    'Ndokwa West',
    'Okpe',
    'Oshimili North',
    'Oshimili South',
    'Patani',
    'Sapele',
    'Udu',
    'Ughelli North',
    'Ughelli South',
    'Ukwuani',
    'Uvwie',
    'Warri North',
    'Warri South',
    'Warri South West'
  ],
  'Ebonyi': [
    'Abakaliki',
    'Afikpo North',
    'Afikpo South',
    'Ebonyi',
    'Ezza North',
    'Ezza South',
    'Ikwo',
    'Ishielu',
    'Ivo',
    'Izzi',
    'Ohaozara',
    'Ohaukwu',
    'Onicha'
  ],
  'Edo': [
    'Akoko-Edo',
    'Egor',
    'Esan Central',
    'Esan North-East',
    'Esan South-East',
    'Esan West',
    'Etsako Central',
    'Etsako East',
    'Etsako West',
    'Igueben',
    'Ikpoba-Okha',
    'Oredo',
    'Orhionmwon',
    'Ovia North-East',
    'Ovia South-West',
    'Owan East',
    'Owan West',
    'Uhunmwonde'
  ],
  'Ekiti': [
    'Ado Ekiti',
    'Efon',
    'Ekiti East',
    'Ekiti South-West',
    'Ekiti West',
    'Emure',
    'Gbonyin',
    'Ido/Osi',
    'Ijero',
    'Ikere',
    'Ikole',
    'Ilejemeje',
    'Irepodun/Ifelodun',
    'Ise/Orun',
    'Moba',
    'Oye'
  ],
  'Enugu': [
    'Aninri',
    'Awgu',
    'Enugu East',
    'Enugu North',
    'Enugu South',
    'Ezeagu',
    'Igbo Etiti',
    'Igbo Eze North',
    'Igbo Eze South',
    'Isi Uzo',
    'Nkanu East',
    'Nkanu West',
    'Nsukka',
    'Oji River',
    'Udenu',
    'Udi',
    'Uzo Uwani'
  ],
  'Gombe': [
    'Akko',
    'Balanga',
    'Billiri',
    'Dukku',
    'Funakaye',
    'Gombe',
    'Kaltungo',
    'Kwami',
    'Nafada',
    'Shongom',
    'Yamaltu/Deba'
  ],
  'Imo': [
    'Aboh Mbaise',
    'Ahiazu Mbaise',
    'Ehime Mbano',
    'Ezinihitte',
    'Ideato North',
    'Ideato South',
    'Ihitte/Uboma',
    'Ikeduru',
    'Isiala Mbano',
    'Isu',
    'Mbaitoli',
    'Ngor Okpala',
    'Njaba',
    'Nkwerre',
    'Nwangele',
    'Obowo',
    'Oguta',
    'Ohaji/Egbema',
    'Okigwe',
    'Onuimo',
    'Orlu',
    'Orsu',
    'Oru East',
    'Oru West',
    'Owerri Municipal',
    'Owerri North',
    'Owerri West'
  ],
  'Jigawa': [
    'Auyo',
    'Babura',
    'Biriniwa',
    'Birnin Kudu',
    'Buji',
    'Dutse',
    'Gagarawa',
    'Garki',
    'Gumel',
    'Guri',
    'Gwaram',
    'Gwiwa',
    'Hadejia',
    'Jahun',
    'Kafin Hausa',
    'Kaugama',
    'Kazaure',
    'Kiri Kasama',
    'Kiyawa',
    'Maigatari',
    'Malam Madori',
    'Miga',
    'Ringim',
    'Roni',
    'Sule Tankarkar',
    'Taura',
    'Yankwashi'
  ],
  'Kaduna': [
    'Birnin Gwari',
    'Chikun',
    'Giwa',
    'Igabi',
    'Ikara',
    'Jaba',
    'Jema\'a',
    'Kachia',
    'Kaduna North',
    'Kaduna South',
    'Kagarko',
    'Kajuru',
    'Kaura',
    'Kauru',
    'Kubau',
    'Kudan',
    'Lere',
    'Makarfi',
    'Sabon Gari',
    'Sanga',
    'Soba',
    'Zangon Kataf',
    'Zaria'
  ],
  'Kano': [
    'Ajingi',
    'Albasu',
    'Bagwai',
    'Bebeji',
    'Bichi',
    'Bunkure',
    'Dala',
    'Dambatta',
    'Dawakin Kudu',
    'Dawakin Tofa',
    'Doguwa',
    'Fagge',
    'Gabasawa',
    'Garko',
    'Garun Mallam',
    'Gaya',
    'Gezawa',
    'Gwale',
    'Gwarzo',
    'Kabo',
    'Kano Municipal',
    'Karaye',
    'Kibiya',
    'Kiru',
    'Kumbotso',
    'Kunchi',
    'Kura',
    'Madobi',
    'Makoda',
    'Minjibir',
    'Nasarawa',
    'Rano',
    'Rimin Gado',
    'Rogo',
    'Shanono',
    'Sumaila',
    'Takai',
    'Tarauni',
    'Tofa',
    'Tsanyawa',
    'Tudun Wada',
    'Ungogo',
    'Warawa',
    'Wudil'
  ],
  'Katsina': [
    'Bakori',
    'Batagarawa',
    'Batsari',
    'Baure',
    'Bindawa',
    'Charanchi',
    'Dandume',
    'Danja',
    'Dan Musa',
    'Daura',
    'Dutsi',
    'Dutsin Ma',
    'Faskari',
    'Funtua',
    'Ingawa',
    'Jibia',
    'Kafur',
    'Kaita',
    'Kankara',
    'Kankia',
    'Katsina',
    'Kurfi',
    'Kusada',
    'Mai\'Adua',
    'Malumfashi',
    'Mani',
    'Mashi',
    'Matazu',
    'Musawa',
    'Rimi',
    'Sabuwa',
    'Safana',
    'Sandamu',
    'Zango'
  ],
  'Kebbi': [
    'Aleiro',
    'Arewa Dandi',
    'Argungu',
    'Augie',
    'Bagudo',
    'Birnin Kebbi',
    'Bunza',
    'Dandi',
    'Fakai',
    'Gwandu',
    'Jega',
    'Kalgo',
    'Koko/Besse',
    'Maiyama',
    'Ngaski',
    'Sakaba',
    'Shanga',
    'Suru',
    'Wasagu/Danko',
    'Yauri',
    'Zuru'
  ],
  'Kogi': [
    'Adavi',
    'Ajaokuta',
    'Ankpa',
    'Bassa',
    'Dekina',
    'Ibaji',
    'Idah',
    'Igalamela Odolu',
    'Ijumu',
    'Kabba/Bunu',
    'Kogi',
    'Lokoja',
    'Mopa Muro',
    'Ofu',
    'Ogori/Magongo',
    'Okehi',
    'Okene',
    'Olamaboro',
    'Omala',
    'Yagba East',
    'Yagba West'
  ],
  'Kwara': [
    'Asa',
    'Baruten',
    'Edu',
    'Ekiti',
    'Ifelodun',
    'Ilorin East',
    'Ilorin South',
    'Ilorin West',
    'Irepodun',
    'Isin',
    'Kaiama',
    'Moro',
    'Offa',
    'Oke Ero',
    'Oyun',
    'Patigi'
  ],
  'Lagos': [
    'Agege',
    'Ajeromi-Ifelodun',
    'Alimosho',
    'Amuwo-Odofin',
    'Apapa',
    'Badagry',
    'Epe',
    'Eti Osa',
    'Ibeju-Lekki',
    'Ifako-Ijaiye',
    'Ikeja',
    'Ikorodu',
    'Kosofe',
    'Lagos Island',
    'Lagos Mainland',
    'Mushin',
    'Ojo',
    'Oshodi-Isolo',
    'Shomolu',
    'Surulere'
  ],
  'Nasarawa': [
    'Akwanga',
    'Awe',
    'Doma',
    'Karu',
    'Keana',
    'Keffi',
    'Kokona',
    'Lafia',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Toto',
    'Wamba'
  ],
  'Niger': [
    'Agaie',
    'Agwara',
    'Bida',
    'Borgu',
    'Bosso',
    'Chanchaga',
    'Edati',
    'Gbako',
    'Gurara',
    'Katcha',
    'Kontagora',
    'Lapai',
    'Lavun',
    'Magama',
    'Mariga',
    'Mashegu',
    'Mokwa',
    'Moya',
    'Paikoro',
    'Rafi',
    'Rijau',
    'Shiroro',
    'Suleja',
    'Tafa',
    'Wushishi'
  ],
  'Ogun': [
    'Abeokuta North',
    'Abeokuta South',
    'Ado-Odo/Ota',
    'Egbado North',
    'Egbado South',
    'Ewekoro',
    'Ifo',
    'Ijebu East',
    'Ijebu North',
    'Ijebu North East',
    'Ijebu Ode',
    'Ikenne',
    'Imeko Afon',
    'Ipokia',
    'Obafemi Owode',
    'Odeda',
    'Odogbolu',
    'Ogun Waterside',
    'Remo North',
    'Shagamu'
  ],
  'Ondo': [
    'Akoko North-East',
    'Akoko North-West',
    'Akoko South-East',
    'Akoko South-West',
    'Akure North',
    'Akure South',
    'Ese Odo',
    'Idanre',
    'Ifedore',
    'Ilaje',
    'Ile Oluji/Okeigbo',
    'Irele',
    'Odigbo',
    'Okitipupa',
    'Ondo East',
    'Ondo West',
    'Ose',
    'Owo'
  ],
  'Osun': [
    'Aiyedaade',
    'Aiyedire',
    'Atakunmosa East',
    'Atakunmosa West',
    'Boluwaduro',
    'Boripe',
    'Ede North',
    'Ede South',
    'Egbedore',
    'Ejigbo',
    'Ife Central',
    'Ife East',
    'Ife North',
    'Ife South',
    'Ifedayo',
    'Ifelodun',
    'Ila',
    'Ilesa East',
    'Ilesa West',
    'Irepodun',
    'Irewole',
    'Isokan',
    'Iwo',
    'Obokun',
    'Odo Otin',
    'Ola Oluwa',
    'Olorunda',
    'Oriade',
    'Orolu',
    'Osogbo'
  ],
  'Oyo': [
    'Afijio',
    'Akinyele',
    'Atiba',
    'Atisbo',
    'Egbeda',
    'Ibadan North',
    'Ibadan North-East',
    'Ibadan North-West',
    'Ibadan South-East',
    'Ibadan South-West',
    'Ibarapa Central',
    'Ibarapa East',
    'Ibarapa North',
    'Ido',
    'Irepo',
    'Iseyin',
    'Itesiwaju',
    'Iwajowa',
    'Kajola',
    'Lagelu',
    'Ogo Oluwa',
    'Ogbomosho North',
    'Ogbomosho South',
    'Olorunsogo',
    'Oluyole',
    'Ona Ara',
    'Orelope',
    'Ori Ire',
    'Oyo East',
    'Oyo West',
    'Saki East',
    'Saki West',
    'Surulere'
  ],
  'Plateau': [
    'Bokkos',
    'Barkin Ladi',
    'Bassa',
    'Jos East',
    'Jos North',
    'Jos South',
    'Kanam',
    'Kanke',
    'Langtang North',
    'Langtang South',
    'Mangu',
    'Mikang',
    'Pankshin',
    'Qua\'an Pan',
    'Riyom',
    'Shendam',
    'Wase'
  ],
  'Rivers': [
    'Abua/Odual',
    'Ahoada East',
    'Ahoada West',
    'Akuku-Toru',
    'Andoni',
    'Asari-Toru',
    'Bonny',
    'Degema',
    'Eleme',
    'Emohua',
    'Etche',
    'Gokana',
    'Ikwerre',
    'Khana',
    'Obio/Akpor',
    'Ogba/Egbema/Ndoni',
    'Ogu/Bolo',
    'Okrika',
    'Omuma',
    'Opobo/Nkoro',
    'Oyigbo',
    'Port Harcourt',
    'Tai'
  ],
  'Sokoto': [
    'Binji',
    'Bodinga',
    'Dange Shuni',
    'Gada',
    'Goronyo',
    'Gudu',
    'Gwadabawa',
    'Illela',
    'Isa',
    'Kebbe',
    'Kware',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Silame',
    'Sokoto North',
    'Sokoto South',
    'Tambuwal',
    'Tangaza',
    'Tureta',
    'Wamako',
    'Wurno',
    'Yabo'
  ],
  'Taraba': [
    'Ardo Kola',
    'Bali',
    'Donga',
    'Gashaka',
    'Gassol',
    'Ibi',
    'Jalingo',
    'Karim Lamido',
    'Kurmi',
    'Lau',
    'Sardauna',
    'Takum',
    'Ussa',
    'Wukari',
    'Yorro',
    'Zing'
  ],
  'Yobe': [
    'Bade',
    'Bursari',
    'Damaturu',
    'Fika',
    'Fune',
    'Geidam',
    'Gujba',
    'Gulani',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Nguru',
    'Potiskum',
    'Tarmuwa',
    'Yunusari',
    'Yusufari'
  ],
  'Zamfara': [
    'Anka',
    'Bakura',
    'Birnin Magaji/Kiyaw',
    'Bukkuyum',
    'Bungudu',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Talata Mafara',
    'Zurmi'
  ],
  'Abuja': [],
};

class Lga {
  final String name;

  Lga({required this.name});
}

class StateModel {
  final String name;
  final List<Lga> lgas;

  StateModel({required this.name, required this.lgas});
}

List<StateModel> states = [
  StateModel(
    name: 'Abia',
    lgas: [
      Lga(name: 'Aba North'),
      Lga(name: 'Aba South'),
      Lga(name: 'Arochukwu'),
      Lga(name: 'Bende'),
      Lga(name: 'Ikwuano'),
      Lga(name: 'Isiala Ngwa North'),
      Lga(name: 'Isiala Ngwa South'),
      Lga(name: 'Isiukwuato'),
      Lga(name: 'Obi Ngwa'),
      Lga(name: 'Ohafia'),
      Lga(name: 'Osisioma'),
      Lga(name: 'Ugwunagbo'),
      Lga(name: 'Ukwa East'),
      Lga(name: 'Ukwa West'),
      Lga(name: 'Umuahia North'),
      Lga(name: 'Umuahia South'),
      Lga(name: 'Umu Nneochi'),
    ],
  ),
  StateModel(
    name: 'Adamawa',
    lgas: [
      Lga(name: 'Demsa'),
      Lga(name: 'Fufore'),
      Lga(name: 'Ganye'),
      Lga(name: 'Gayuk'),
      Lga(name: 'Girei'),
      Lga(name: 'Gombi'),
      Lga(name: 'Guyuk'),
      Lga(name: 'Hong'),
      Lga(name: 'Jada'),
      Lga(name: 'Lamurde'),
      Lga(name: 'Madagali'),
      Lga(name: 'Maiha'),
      Lga(name: 'Mayo Belwa'),
      Lga(name: 'Michika'),
      Lga(name: 'Mubi North'),
      Lga(name: 'Mubi South'),
      Lga(name: 'Numan'),
      Lga(name: 'Shelleng'),
      Lga(name: 'Song'),
      Lga(name: 'Toungo'),
      Lga(name: 'Yola North'),
      Lga(name: 'Yola South'),
    ],
  ),
  StateModel(
    name: 'Akwa Ibom',
    lgas: [
      Lga(name: 'Abak'),
      Lga(name: 'Eastern Obolo'),
      Lga(name: 'Eket'),
      Lga(name: 'Esit Eket'),
      Lga(name: 'Essien Udim'),
      Lga(name: 'Etim Ekpo'),
      Lga(name: 'Etinan'),
      Lga(name: 'Ibeno'),
      Lga(name: 'Ibesikpo Asutan'),
      Lga(name: 'Ibiono-Ibom'),
      Lga(name: 'Ika'),
      Lga(name: 'Ikono'),
      Lga(name: 'Ikot Abasi'),
      Lga(name: 'Ikot Ekpene'),
      Lga(name: 'Ini'),
      Lga(name: 'Itu'),
      Lga(name: 'Mbo'),
      Lga(name: 'Mkpat-Enin'),
      Lga(name: 'Nsit-Atai'),
      Lga(name: 'Nsit-Ibom'),
      Lga(name: 'Nsit-Ubium'),
      Lga(name: 'Obot Akara'),
      Lga(name: 'Okobo'),
      Lga(name: 'Onna'),
      Lga(name: 'Oron'),
      Lga(name: 'Oruk Anam'),
      Lga(name: 'Udung-Uko'),
      Lga(name: 'Ukanafun'),
      Lga(name: 'Uruan'),
      Lga(name: 'Urue-Offong/Oruko'),
      Lga(name: 'Uyo'),
    ],
  ),
  StateModel(
    name: 'Anambra',
    lgas: [
      Lga(name: 'Aguata'),
      Lga(name: 'Anambra East'),
      Lga(name: 'Anambra West'),
      Lga(name: 'Anaocha'),
      Lga(name: 'Awka North'),
      Lga(name: 'Awka South'),
      Lga(name: 'Ayamelum'),
      Lga(name: 'Dunukofia'),
      Lga(name: 'Ekwusigo'),
      Lga(name: 'Idemili North'),
      Lga(name: 'Idemili South'),
      Lga(name: 'Ihiala'),
      Lga(name: 'Njikoka'),
      Lga(name: 'Nnewi North'),
      Lga(name: 'Nnewi South'),
      Lga(name: 'Ogbaru'),
      Lga(name: 'Onitsha North'),
      Lga(name: 'Onitsha South'),
      Lga(name: 'Orumba North'),
      Lga(name: 'Orumba South'),
      Lga(name: 'Oyi'),
    ],
  ),
  StateModel(
    name: 'Bauchi',
    lgas: [
      Lga(name: 'Alkaleri'),
      Lga(name: 'Bauchi'),
      Lga(name: 'Bogoro'),
      Lga(name: 'Damban'),
      Lga(name: 'Darazo'),
      Lga(name: 'Dass'),
      Lga(name: 'Ganjuwa'),
      Lga(name: 'Giade'),
      Lga(name: 'Itas/Gadau'),
      Lga(name: 'Jama\'are'),
      Lga(name: 'Katagum'),
      Lga(name: 'Kirfi'),
      Lga(name: 'Misau'),
      Lga(name: 'Ningi'),
      Lga(name: 'Shira'),
      Lga(name: 'Tafawa Balewa'),
      Lga(name: 'Toro'),
      Lga(name: 'Warji'),
      Lga(name: 'Zaki'),
    ],
  ),
  StateModel(
    name: 'Bayelsa',
    lgas: [
      Lga(name: 'Brass'),
      Lga(name: 'Ekeremor'),
      Lga(name: 'Kolokuma/Opokuma'),
      Lga(name: 'Nembe'),
      Lga(name: 'Ogbia'),
      Lga(name: 'Sagbama'),
      Lga(name: 'Southern Ijaw'),
      Lga(name: 'Yenagoa'),
    ],
  ),
  StateModel(
    name: 'Benue',
    lgas: [
      Lga(name: 'Ado'),
      Lga(name: 'Agatu'),
      Lga(name: 'Apa'),
      Lga(name: 'Buruku'),
      Lga(name: 'Gboko'),
      Lga(name: 'Guma'),
      Lga(name: 'Gwer East'),
      Lga(name: 'Gwer West'),
      Lga(name: 'Katsina-Ala'),
      Lga(name: 'Konshisha'),
      Lga(name: 'Kwande'),
      Lga(name: 'Logo'),
      Lga(name: 'Makurdi'),
      Lga(name: 'Obi'),
      Lga(name: 'Ogbadibo'),
      Lga(name: 'Ohimini'),
      Lga(name: 'Oju'),
      Lga(name: 'Okpokwu'),
      Lga(name: 'Otukpo'),
      Lga(name: 'Tarka'),
      Lga(name: 'Ukum'),
      Lga(name: 'Ushongo'),
      Lga(name: 'Vandeikya'),
    ],
  ),
  StateModel(
    name: 'Abia',
    lgas: [
      Lga(name: 'Aba North'),
      Lga(name: 'Aba South'),
      Lga(name: 'Arochukwu'),
      Lga(name: 'Bende'),
      Lga(name: 'Ikwuano'),
      Lga(name: 'Isiala Ngwa North'),
      Lga(name: 'Isiala Ngwa South'),
      Lga(name: 'Isiukwuato'),
      Lga(name: 'Obi Ngwa'),
      Lga(name: 'Ohafia'),
      Lga(name: 'Osisioma'),
      Lga(name: 'Ugwunagbo'),
      Lga(name: 'Ukwa East'),
      Lga(name: 'Ukwa West'),
      Lga(name: 'Umuahia North'),
      Lga(name: 'Umuahia South'),
      Lga(name: 'Umu Nneochi'),
    ],
  ),
  StateModel(
    name: 'Adamawa',
    lgas: [
      Lga(name: 'Demsa'),
      Lga(name: 'Fufore'),
      Lga(name: 'Ganye'),
      Lga(name: 'Gayuk'),
      Lga(name: 'Girei'),
      Lga(name: 'Gombi'),
      Lga(name: 'Guyuk'),
      Lga(name: 'Hong'),
      Lga(name: 'Jada'),
      Lga(name: 'Lamurde'),
      Lga(name: 'Madagali'),
      Lga(name: 'Maiha'),
      Lga(name: 'Mayo Belwa'),
      Lga(name: 'Michika'),
      Lga(name: 'Mubi North'),
      Lga(name: 'Mubi South'),
      Lga(name: 'Numan'),
      Lga(name: 'Shelleng'),
      Lga(name: 'Song'),
      Lga(name: 'Toungo'),
      Lga(name: 'Yola North'),
      Lga(name: 'Yola South'),
    ],
  ),
  StateModel(
    name: 'Akwa Ibom',
    lgas: [
      Lga(name: 'Abak'),
      Lga(name: 'Eastern Obolo'),
      Lga(name: 'Eket'),
      Lga(name: 'Esit Eket'),
      Lga(name: 'Essien Udim'),
      Lga(name: 'Etim Ekpo'),
      Lga(name: 'Etinan'),
      Lga(name: 'Ibeno'),
      Lga(name: 'Ibesikpo Asutan'),
      Lga(name: 'Ibiono-Ibom'),
      Lga(name: 'Ika'),
      Lga(name: 'Ikono'),
      Lga(name: 'Ikot Abasi'),
      Lga(name: 'Ikot Ekpene'),
      Lga(name: 'Ini'),
      Lga(name: 'Itu'),
      Lga(name: 'Mbo'),
      Lga(name: 'Mkpat-Enin'),
      Lga(name: 'Nsit-Atai'),
      Lga(name: 'Nsit-Ibom'),
      Lga(name: 'Nsit-Ubium'),
      Lga(name: 'Obot Akara'),
      Lga(name: 'Okobo'),
      Lga(name: 'Onna'),
      Lga(name: 'Oron'),
      Lga(name: 'Oruk Anam'),
      Lga(name: 'Udung-Uko'),
      Lga(name: 'Ukanafun'),
      Lga(name: 'Uruan'),
      Lga(name: 'Urue-Offong/Oruko'),
      Lga(name: 'Uyo'),
    ],
  ),
  StateModel(
    name: 'Anambra',
    lgas: [
      Lga(name: 'Aguata'),
      Lga(name: 'Anambra East'),
      Lga(name: 'Anambra West'),
      Lga(name: 'Anaocha'),
      Lga(name: 'Awka North'),
      Lga(name: 'Awka South'),
      Lga(name: 'Ayamelum'),
      Lga(name: 'Dunukofia'),
      Lga(name: 'Ekwusigo'),
      Lga(name: 'Idemili North'),
      Lga(name: 'Idemili South'),
      Lga(name: 'Ihiala'),
      Lga(name: 'Njikoka'),
      Lga(name: 'Nnewi North'),
      Lga(name: 'Nnewi South'),
      Lga(name: 'Ogbaru'),
      Lga(name: 'Onitsha North'),
      Lga(name: 'Onitsha South'),
      Lga(name: 'Orumba North'),
      Lga(name: 'Orumba South'),
      Lga(name: 'Oyi'),
    ],
  ),
  StateModel(
    name: 'Bauchi',
    lgas: [
      Lga(name: 'Alkaleri'),
      Lga(name: 'Bauchi'),
      Lga(name: 'Bogoro'),
      Lga(name: 'Damban'),
      Lga(name: 'Darazo'),
      Lga(name: 'Dass'),
      Lga(name: 'Ganjuwa'),
      Lga(name: 'Giade'),
      Lga(name: 'Itas/Gadau'),
      Lga(name: 'Jama\'are'),
      Lga(name: 'Katagum'),
      Lga(name: 'Kirfi'),
      Lga(name: 'Misau'),
      Lga(name: 'Ningi'),
      Lga(name: 'Shira'),
      Lga(name: 'Tafawa Balewa'),
      Lga(name: 'Toro'),
      Lga(name: 'Warji'),
      Lga(name: 'Zaki'),
    ],
  ),
  StateModel(
    name: 'Bayelsa',
    lgas: [
      Lga(name: 'Brass'),
      Lga(name: 'Ekeremor'),
      Lga(name: 'Kolokuma/Opokuma'),
      Lga(name: 'Nembe'),
      Lga(name: 'Ogbia'),
      Lga(name: 'Sagbama'),
      Lga(name: 'Southern Ijaw'),
      Lga(name: 'Yenagoa'),
    ],
  ),
  StateModel(
    name: 'Benue',
    lgas: [
      Lga(name: 'Ado'),
      Lga(name: 'Agatu'),
      Lga(name: 'Apa'),
      Lga(name: 'Buruku'),
      Lga(name: 'Gboko'),
      Lga(name: 'Guma'),
      Lga(name: 'Gwer East'),
      Lga(name: 'Gwer West'),
      Lga(name: 'Katsina-Ala'),
      Lga(name: 'Konshisha'),
      Lga(name: 'Kwande'),
      Lga(name: 'Logo'),
      Lga(name: 'Makurdi'),
      Lga(name: 'Obi'),
      Lga(name: 'Ogbadibo'),
      Lga(name: 'Ohimini'),
      Lga(name: 'Oju'),
      Lga(name: 'Okpokwu'),
      Lga(name: 'Otukpo'),
      Lga(name: 'Tarka'),
      Lga(name: 'Ukum'),
      Lga(name: 'Ushongo'),
      Lga(name: 'Vandeikya'),
    ],
  ),
  StateModel(
    name: 'Borno',
    lgas: [
      Lga(name: 'Abadam'),
      Lga(name: 'Askira/Uba'),
      Lga(name: 'Bama'),
      Lga(name: 'Bayo'),
      Lga(name: 'Biu'),
      Lga(name: 'Chibok'),
      Lga(name: 'Damboa'),
      Lga(name: 'Dikwa'),
      Lga(name: 'Gubio'),
      Lga(name: 'Guzamala'),
      Lga(name: 'Gwoza'),
      Lga(name: 'Hawul'),
      Lga(name: 'Jere'),
      Lga(name: 'Kaga'),
      Lga(name: 'Kala/Balge'),
      Lga(name: 'Konduga'),
      Lga(name: 'Kukawa'),
      Lga(name: 'Kwaya Kusar'),
      Lga(name: 'Mafa'),
      Lga(name: 'Magumeri'),
      Lga(name: 'Maiduguri'),
      Lga(name: 'Marte'),
      Lga(name: 'Mobbar'),
      Lga(name: 'Monguno'),
      Lga(name: 'Ngala'),
      Lga(name: 'Nganzai'),
      Lga(name: 'Shani'),
    ],
  ),
  StateModel(
    name: 'Cross River',
    lgas: [
      Lga(name: 'Abi'),
      Lga(name: 'Akamkpa'),
      Lga(name: 'Akpabuyo'),
      Lga(name: 'Bakassi'),
      Lga(name: 'Bekwara'),
      Lga(name: 'Biase'),
      Lga(name: 'Boki'),
      Lga(name: 'Calabar Municipal'),
      Lga(name: 'Calabar South'),
      Lga(name: 'Etung'),
      Lga(name: 'Ikom'),
      Lga(name: 'Obanliku'),
      Lga(name: 'Obubra'),
      Lga(name: 'Obudu'),
      Lga(name: 'Odukpani'),
      Lga(name: 'Ogoja'),
      Lga(name: 'Yakuur'),
      Lga(name: 'Yala'),
    ],
  ),
  StateModel(
    name: 'Delta',
    lgas: [
      Lga(name: 'Aniocha North'),
      Lga(name: 'Aniocha South'),
      Lga(name: 'Bomadi'),
      Lga(name: 'Burutu'),
      Lga(name: 'Ethiope East'),
      Lga(name: 'Ethiope West'),
      Lga(name: 'Ika North East'),
      Lga(name: 'Ika South'),
      Lga(name: 'Isoko North'),
      Lga(name: 'Isoko South'),
      Lga(name: 'Ndokwa East'),
      Lga(name: 'Ndokwa West'),
      Lga(name: 'Okpe'),
      Lga(name: 'Oshimili North'),
      Lga(name: 'Oshimili South'),
      Lga(name: 'Patani'),
      Lga(name: 'Sapele'),
      Lga(name: 'Udu'),
      Lga(name: 'Ughelli North'),
      Lga(name: 'Ughelli South'),
      Lga(name: 'Ukwuani'),
      Lga(name: 'Uvwie'),
      Lga(name: 'Warri North'),
      Lga(name: 'Warri South'),
      Lga(name: 'Warri South West'),
    ],
  ),
  StateModel(
    name: 'Ebonyi',
    lgas: [
      Lga(name: 'Abakaliki'),
      Lga(name: 'Afikpo North'),
      Lga(name: 'Afikpo South'),
      Lga(name: 'Ebonyi'),
      Lga(name: 'Ezza North'),
      Lga(name: 'Ezza South'),
      Lga(name: 'Ikwo'),
      Lga(name: 'Ishielu'),
      Lga(name: 'Ivo'),
      Lga(name: 'Izzi'),
      Lga(name: 'Ohaozara'),
      Lga(name: 'Ohaukwu'),
      Lga(name: 'Onicha'),
    ],
  ),
  StateModel(
    name: 'Edo',
    lgas: [
      Lga(name: 'Akoko-Edo'),
      Lga(name: 'Egor'),
      Lga(name: 'Esan Central'),
      Lga(name: 'Esan North-East'),
      Lga(name: 'Esan South-East'),
      Lga(name: 'Esan West'),
      Lga(name: 'Etsako Central'),
      Lga(name: 'Etsako East'),
      Lga(name: 'Etsako West'),
      Lga(name: 'Igueben'),
      Lga(name: 'Ikpoba-Okha'),
      Lga(name: 'Oredo'),
      Lga(name: 'Orhionmwon'),
      Lga(name: 'Ovia North-East'),
      Lga(name: 'Ovia South-West'),
      Lga(name: 'Owan East'),
      Lga(name: 'Owan West'),
      Lga(name: 'Uhunmwonde'),
    ],
  ),
  StateModel(
    name: 'Ekiti',
    lgas: [
      Lga(name: 'Ado-Ekiti'),
      Lga(name: 'Efon'),
      Lga(name: 'Ekiti East'),
      Lga(name: 'Ekiti South-West'),
      Lga(name: 'Ekiti West'),
      Lga(name: 'Emure'),
      Lga(name: 'Gbonyin'),
      Lga(name: 'Ido-Osi'),
      Lga(name: 'Ijero'),
      Lga(name: 'Ikere'),
      Lga(name: 'Ikole'),
      Lga(name: 'Ilejemeje'),
      Lga(name: 'Irepodun/Ifelodun'),
      Lga(name: 'Ise/Orun'),
      Lga(name: 'Moba'),
      Lga(name: 'Oye'),
    ],
  ),
  StateModel(
    name: 'Enugu',
    lgas: [
      Lga(name: 'Aninri'),
      Lga(name: 'Awgu'),
      Lga(name: 'Enugu East'),
      Lga(name: 'Enugu North'),
      Lga(name: 'Enugu South'),
      Lga(name: 'Ezeagu'),
      Lga(name: 'Igbo Etiti'),
      Lga(name: 'Igbo Eze North'),
      Lga(name: 'Igbo Eze South'),
      Lga(name: 'Isi Uzo'),
      Lga(name: 'Nkanu East'),
      Lga(name: 'Nkanu West'),
      Lga(name: 'Nsukka'),
      Lga(name: 'Oji River'),
      Lga(name: 'Udenu'),
      Lga(name: 'Udi'),
      Lga(name: 'Uzo-Uwani'),
    ],
  ),
  StateModel(
    name: 'Gombe',
    lgas: [
      Lga(name: 'Akko'),
      Lga(name: 'Balanga'),
      Lga(name: 'Billiri'),
      Lga(name: 'Dukku'),
      Lga(name: 'Funakaye'),
      Lga(name: 'Gombe'),
      Lga(name: 'Kaltungo'),
      Lga(name: 'Kwami'),
      Lga(name: 'Nafada'),
      Lga(name: 'Shongom'),
      Lga(name: 'Yamaltu/Deba'),
    ],
  ),
  StateModel(
    name: 'Imo',
    lgas: [
      Lga(name: 'Aboh Mbaise'),
      Lga(name: 'Ahiazu Mbaise'),
      Lga(name: 'Ehime Mbano'),
      Lga(name: 'Ezinihitte'),
      Lga(name: 'Ideato North'),
      Lga(name: 'Ideato South'),
      Lga(name: 'Ihitte/Uboma'),
      Lga(name: 'Ikeduru'),
      Lga(name: 'Isiala Mbano'),
      Lga(name: 'Isu'),
      Lga(name: 'Mbaitoli'),
      Lga(name: 'Ngor Okpala'),
      Lga(name: 'Njaba'),
      Lga(name: 'Nkwerre'),
      Lga(name: 'Nwangele'),
      Lga(name: 'Obowo'),
      Lga(name: 'Oguta'),
      Lga(name: 'Ohaji/Egbema'),
      Lga(name: 'Okigwe'),
      Lga(name: 'Onuimo'),
      Lga(name: 'Orlu'),
      Lga(name: 'Orsu'),
      Lga(name: 'Oru East'),
      Lga(name: 'Oru West'),
      Lga(name: 'Owerri Municipal'),
      Lga(name: 'Owerri North'),
      Lga(name: 'Owerri West'),
    ],
  ),
  StateModel(
    name: 'Jigawa',
    lgas: [
      Lga(name: 'Auyo'),
      Lga(name: 'Babura'),
      Lga(name: 'Biriniwa'),
      Lga(name: 'Birnin Kudu'),
      Lga(name: 'Buji'),
      Lga(name: 'Dutse'),
      Lga(name: 'Gagarawa'),
      Lga(name: 'Garki'),
      Lga(name: 'Gumel'),
      Lga(name: 'Guri'),
      Lga(name: 'Gwaram'),
      Lga(name: 'Gwiwa'),
      Lga(name: 'Hadejia'),
      Lga(name: 'Jahun'),
      Lga(name: 'Kafin Hausa'),
      Lga(name: 'Kaugama'),
      Lga(name: 'Kazaure'),
      Lga(name: 'Kiri Kasama'),
      Lga(name: 'Kiyawa'),
      Lga(name: 'Maigatari'),
      Lga(name: 'Malam Madori'),
      Lga(name: 'Miga'),
      Lga(name: 'Ringim'),
      Lga(name: 'Roni'),
      Lga(name: 'Sule Tankarkar'),
      Lga(name: 'Taura'),
      Lga(name: 'Yankwashi'),
    ],
  ),
  StateModel(
    name: 'Kaduna',
    lgas: [
      Lga(name: 'Birnin Gwari'),
      Lga(name: 'Chikun'),
      Lga(name: 'Giwa'),
      Lga(name: 'Igabi'),
      Lga(name: 'Ikara'),
      Lga(name: 'Jaba'),
      Lga(name: 'Jema\'a'),
      Lga(name: 'Kachia'),
      Lga(name: 'Kaduna North'),
      Lga(name: 'Kaduna South'),
      Lga(name: 'Kagarko'),
      Lga(name: 'Kajuru'),
      Lga(name: 'Kaura'),
      Lga(name: 'Kauru'),
      Lga(name: 'Kubau'),
      Lga(name: 'Kudan'),
      Lga(name: 'Lere'),
      Lga(name: 'Makarfi'),
      Lga(name: 'Sabon Gari'),
      Lga(name: 'Sanga'),
      Lga(name: 'Soba'),
      Lga(name: 'Zangon Kataf'),
      Lga(name: 'Zaria'),
    ],
  ),
  StateModel(
    name: 'Kano',
    lgas: [
      Lga(name: 'Ajingi'),
      Lga(name: 'Albasu'),
      Lga(name: 'Bagwai'),
      Lga(name: 'Bebeji'),
      Lga(name: 'Bichi'),
      Lga(name: 'Bunkure'),
      Lga(name: 'Dala'),
      Lga(name: 'Dambatta'),
      Lga(name: 'Dawakin Kudu'),
      Lga(name: 'Dawakin Tofa'),
      Lga(name: 'Doguwa'),
      Lga(name: 'Fagge'),
      Lga(name: 'Gabasawa'),
      Lga(name: 'Garko'),
      Lga(name: 'Garun Mallam'),
      Lga(name: 'Gaya'),
      Lga(name: 'Gezawa'),
      Lga(name: 'Gwale'),
      Lga(name: 'Gwarzo'),
      Lga(name: 'Kabo'),
      Lga(name: 'Kano Municipal'),
      Lga(name: 'Karaye'),
      Lga(name: 'Kibiya'),
      Lga(name: 'Kiru'),
      Lga(name: 'Kumbotso'),
      Lga(name: 'Kunchi'),
      Lga(name: 'Kura'),
      Lga(name: 'Madobi'),
      Lga(name: 'Makoda'),
      Lga(name: 'Minjibir'),
      Lga(name: 'Nasarawa'),
      Lga(name: 'Rano'),
      Lga(name: 'Rimin Gado'),
      Lga(name: 'Rogo'),
      Lga(name: 'Shanono'),
      Lga(name: 'Sumaila'),
      Lga(name: 'Takai'),
      Lga(name: 'Tarauni'),
      Lga(name: 'Tofa'),
      Lga(name: 'Tsanyawa'),
      Lga(name: 'Tudun Wada'),
      Lga(name: 'Ungogo'),
      Lga(name: 'Warawa'),
      Lga(name: 'Wudil'),
    ],
  ),
  StateModel(
    name: 'Katsina',
    lgas: [
      Lga(name: 'Bakori'),
      Lga(name: 'Batagarawa'),
      Lga(name: 'Batsari'),
      Lga(name: 'Baure'),
      Lga(name: 'Bindawa'),
      Lga(name: 'Charanchi'),
      Lga(name: 'Dandume'),
      Lga(name: 'Danja'),
      Lga(name: 'Dan Musa'),
      Lga(name: 'Daura'),
      Lga(name: 'Dutsi'),
      Lga(name: 'Dutsin Ma'),
      Lga(name: 'Faskari'),
      Lga(name: 'Funtua'),
      Lga(name: 'Ingawa'),
      Lga(name: 'Jibia'),
      Lga(name: 'Kafur'),
      Lga(name: 'Kaita'),
      Lga(name: 'Kankara'),
      Lga(name: 'Kankia'),
      Lga(name: 'Katsina'),
      Lga(name: 'Kurfi'),
      Lga(name: 'Kusada'),
      Lga(name: 'Mai\'Adua'),
      Lga(name: 'Malumfashi'),
      Lga(name: 'Mani'),
      Lga(name: 'Mashi'),
      Lga(name: 'Matazu'),
      Lga(name: 'Musawa'),
      Lga(name: 'Rimi'),
      Lga(name: 'Sabuwa'),
      Lga(name: 'Safana'),
      Lga(name: 'Sandamu'),
      Lga(name: 'Zango'),
    ],
  ),
  StateModel(
    name: 'Kebbi',
    lgas: [
      Lga(name: 'Aleiro'),
      Lga(name: 'Arewa Dandi'),
      Lga(name: 'Argungu'),
      Lga(name: 'Augie'),
      Lga(name: 'Bagudo'),
      Lga(name: 'Birnin Kebbi'),
      Lga(name: 'Bunza'),
      Lga(name: 'Dandi'),
      Lga(name: 'Fakai'),
      Lga(name: 'Gwandu'),
      Lga(name: 'Jega'),
      Lga(name: 'Kalgo'),
      Lga(name: 'Koko/Besse'),
      Lga(name: 'Maiyama'),
      Lga(name: 'Ngaski'),
      Lga(name: 'Sakaba'),
      Lga(name: 'Shanga'),
      Lga(name: 'Suru'),
      Lga(name: 'Wasagu/Danko'),
      Lga(name: 'Yauri'),
      Lga(name: 'Zuru'),
    ],
  ),
  StateModel(
    name: 'Kogi',
    lgas: [
      Lga(name: 'Adavi'),
      Lga(name: 'Ajaokuta'),
      Lga(name: 'Ankpa'),
      Lga(name: 'Bassa'),
      Lga(name: 'Dekina'),
      Lga(name: 'Ibaji'),
      Lga(name: 'Idah'),
      Lga(name: 'Igalamela Odolu'),
      Lga(name: 'Ijumu'),
      Lga(name: 'Kabba/Bunu'),
      Lga(name: 'Kogi'),
      Lga(name: 'Lokoja'),
      Lga(name: 'Mopa-Muro'),
      Lga(name: 'Ofu'),
      Lga(name: 'Ogori/Magongo'),
      Lga(name: 'Okehi'),
      Lga(name: 'Okene'),
      Lga(name: 'Olamaboro'),
      Lga(name: 'Omala'),
      Lga(name: 'Yagba East'),
      Lga(name: 'Yagba West'),
    ],
  ),
  StateModel(
    name: 'Kwara',
    lgas: [
      Lga(name: 'Asa'),
      Lga(name: 'Baruten'),
      Lga(name: 'Edu'),
      Lga(name: 'Ekiti'),
      Lga(name: 'Ifelodun'),
      Lga(name: 'Ilorin East'),
      Lga(name: 'Ilorin South'),
      Lga(name: 'Ilorin West'),
      Lga(name: 'Irepodun'),
      Lga(name: 'Isin'),
      Lga(name: 'Kaiama'),
      Lga(name: 'Moro'),
      Lga(name: 'Offa'),
      Lga(name: 'Oke Ero'),
      Lga(name: 'Oyun'),
      Lga(name: 'Pategi'),
    ],
  ),
  StateModel(
    name: 'Lagos',
    lgas: [
      Lga(name: 'Agege'),
      Lga(name: 'Ajeromi-Ifelodun'),
      Lga(name: 'Alimosho'),
      Lga(name: 'Amuwo-Odofin'),
      Lga(name: 'Apapa'),
      Lga(name: 'Badagry'),
      Lga(name: 'Epe'),
      Lga(name: 'Eti Osa'),
      Lga(name: 'Ibeju-Lekki'),
      Lga(name: 'Ifako-Ijaiye'),
      Lga(name: 'Ikeja'),
      Lga(name: 'Ikorodu'),
      Lga(name: 'Kosofe'),
      Lga(name: 'Lagos Island'),
      Lga(name: 'Lagos Mainland'),
      Lga(name: 'Mushin'),
      Lga(name: 'Ojo'),
      Lga(name: 'Oshodi-Isolo'),
      Lga(name: 'Shomolu'),
      Lga(name: 'Surulere'),
    ],
  ),
  StateModel(
    name: 'Nasarawa',
    lgas: [
      Lga(name: 'Akwanga'),
      Lga(name: 'Assakio'),
      Lga(name: 'Doma'),
      Lga(name: 'Karu'),
      Lga(name: 'Keffi'),
      Lga(name: 'Kokona'),
      Lga(name: 'Lafia'),
      Lga(name: 'Nasarawa Egon'),
      Lga(name: 'Obi'),
      Lga(name: 'Toto'),
      Lga(name: 'Wamba'),
    ],
  ),
  StateModel(
    name: 'Niger',
    lgas: [
      Lga(name: 'Agaie'),
      Lga(name: 'Agwara'),
      Lga(name: 'Bida'),
      Lga(name: 'Borgu'),
      Lga(name: 'Bosso'),
      Lga(name: 'Chanchaga'),
      Lga(name: 'Edati'),
      Lga(name: 'Gbako'),
      Lga(name: 'Gurara'),
      Lga(name: 'Katcha'),
      Lga(name: 'Lapai'),
      Lga(name: 'Lavun'),
      Lga(name: 'Magama'),
      Lga(name: 'Mariga'),
      Lga(name: 'Mokwa'),
      Lga(name: 'Paikoro'),
      Lga(name: 'Rafi'),
      Lga(name: 'Rijau'),
      Lga(name: 'Shiroro'),
      Lga(name: 'Suleja'),
      Lga(name: 'Wushishi'),
    ],
  ),
  StateModel(
    name: 'Ogun',
    lgas: [
      Lga(name: 'Abeokuta North'),
      Lga(name: 'Abeokuta South'),
      Lga(name: 'Ado-Odo/Ota'),
      Lga(name: 'Egbado North'),
      Lga(name: 'Egbado South'),
      Lga(name: 'Egba North'),
      Lga(name: 'Egba South'),
      Lga(name: 'Ifo'),
      Lga(name: 'Ijebu East'),
      Lga(name: 'Ijebu North'),
      Lga(name: 'Ijebu North East'),
      Lga(name: 'Ijebu Ode'),
      Lga(name: 'Obafemi-Owode'),
      Lga(name: 'Odeda'),
      Lga(name: 'Odogbolu'),
      Lga(name: 'Remo North'),
      Lga(name: 'Sagamu'),
      Lga(name: 'Shagamu'),
      Lga(name: 'Yewa North'),
      Lga(name: 'Yewa South'),
    ],
  ),
  StateModel(
    name: 'Ondo',
    lgas: [
      Lga(name: 'Akoko North-East'),
      Lga(name: 'Akoko North-West'),
      Lga(name: 'Akoko South-East'),
      Lga(name: 'Akoko South-West'),
      Lga(name: 'Akure North'),
      Lga(name: 'Akure South'),
      Lga(name: 'Ese Odo'),
      Lga(name: 'Idanre'),
      Lga(name: 'Ifedore'),
      Lga(name: 'Ilaje'),
      Lga(name: 'Ileoluji/Okeigbo'),
      Lga(name: 'Odigbo'),
      Lga(name: 'Okitipupa'),
      Lga(name: 'Ondo East'),
      Lga(name: 'Ondo West'),
      Lga(name: 'Ose'),
      Lga(name: 'Owo'),
    ],
  ),
  StateModel(
    name: 'Osun',
    lgas: [
      Lga(name: 'Aiyedade'),
      Lga(name: 'Aiyedire'),
      Lga(name: 'Atakunmosa East'),
      Lga(name: 'Atakunmosa West'),
      Lga(name: 'Boluwaduro'),
      Lga(name: 'Boripe'),
      Lga(name: 'Ejigbo'),
      Lga(name: 'Ife Central'),
      Lga(name: 'Ife East'),
      Lga(name: 'Ife North'),
      Lga(name: 'Ife South'),
      Lga(name: 'Ilesa East'),
      Lga(name: 'Ilesa West'),
      Lga(name: 'Isokan'),
      Lga(name: 'Obokun'),
      Lga(name: 'Odo Otin'),
      Lga(name: 'Ola Oluwa'),
      Lga(name: 'Oluyole'),
      Lga(name: 'Osogbo'),
      Lga(name: 'Worado'),
    ],
  ),
  StateModel(
    name: 'Oyo',
    lgas: [
      Lga(name: 'Akinyele'),
      Lga(name: 'Atiba'),
      Lga(name: 'Atisbo'),
      Lga(name: 'Egbeda'),
      Lga(name: 'Ibadan North'),
      Lga(name: 'Ibadan North-East'),
      Lga(name: 'Ibadan North-West'),
      Lga(name: 'Ibadan South-East'),
      Lga(name: 'Ibadan South-West'),
      Lga(name: 'Ibarapa Central'),
      Lga(name: 'Ibarapa East'),
      Lga(name: 'Ibarapa North'),
      Lga(name: 'Ido'),
      Lga(name: 'Iseyin'),
      Lga(name: 'Itesiwaju'),
      Lga(name: 'Itesiwaju'),
      Lga(name: 'Ogbomosho North'),
      Lga(name: 'Ogbomosho South'),
      Lga(name: 'Oyo East'),
      Lga(name: 'Oyo West'),
      Lga(name: 'Saki East'),
      Lga(name: 'Saki West'),
    ],
  ),
  StateModel(
    name: 'Plateau',
    lgas: [
      Lga(name: 'Bokkos'),
      Lga(name: 'Jos East'),
      Lga(name: 'Jos North'),
      Lga(name: 'Jos South'),
      Lga(name: 'Kanam'),
      Lga(name: 'Kanke'),
      Lga(name: 'Langtang North'),
      Lga(name: 'Langtang South'),
      Lga(name: 'Mangu'),
      Lga(name: 'Pankshin'),
      Lga(name: 'Quaan Pan'),
      Lga(name: 'Riyom'),
      Lga(name: 'Shendam'),
      Lga(name: 'Wase'),
    ],
  ),
  StateModel(
    name: 'Rivers',
    lgas: [
      Lga(name: 'Abua/Odual'),
      Lga(name: 'Ahoada East'),
      Lga(name: 'Ahoada West'),
      Lga(name: 'Akuku-Toru'),
      Lga(name: 'Andoni'),
      Lga(name: 'Asari-Toru'),
      Lga(name: 'Bonny'),
      Lga(name: 'Degema'),
      Lga(name: 'Emohua'),
      Lga(name: 'Etche'),
      Lga(name: 'Ikwerre'),
      Lga(name: 'Khana'),
      Lga(name: 'Obio/Akpor'),
      Lga(name: 'Ogba/Egbema/Ndoni'),
      Lga(name: 'Ogu/Bolo'),
      Lga(name: 'Okrika'),
      Lga(name: 'Opobo/Nkoro'),
      Lga(name: 'Port Harcourt'),
      Lga(name: 'Tai'),
    ],
  ),
  StateModel(
    name: 'Sokoto',
    lgas: [
      Lga(name: 'Binji'),
      Lga(name: 'Bodinga'),
      Lga(name: 'Dange Shuni'),
      Lga(name: 'Gada'),
      Lga(name: 'Goronyo'),
      Lga(name: 'Gudu'),
      Lga(name: 'Illela'),
      Lga(name: 'Kebbe'),
      Lga(name: 'Kware'),
      Lga(name: 'Rabah'),
      Lga(name: 'Sabon Birni'),
      Lga(name: 'Shagari'),
      Lga(name: 'Sokoto North'),
      Lga(name: 'Sokoto South'),
      Lga(name: 'Tambuwal'),
      Lga(name: 'Wamakko'),
      Lga(name: 'Wurno'),
      Lga(name: 'Yabo'),
    ],
  ),
  StateModel(
    name: 'Taraba',
    lgas: [
      Lga(name: 'Ardo Kola'),
      Lga(name: 'Bali'),
      Lga(name: 'Donga'),
      Lga(name: 'Gashaka'),
      Lga(name: 'Gassol'),
      Lga(name: 'Jalingo'),
      Lga(name: 'Karin-Lamido'),
      Lga(name: 'Kurmi'),
      Lga(name: 'Lau'),
      Lga(name: 'Sardauna'),
      Lga(name: 'Takum'),
      Lga(name: 'Ussa'),
      Lga(name: 'Wukari'),
      Lga(name: 'Yorro'),
      Lga(name: 'Zing'),
    ],
  ),
  StateModel(
    name: 'Yobe',
    lgas: [
      Lga(name: 'Bade'),
      Lga(name: 'Bursari'),
      Lga(name: 'Damaturu'),
      Lga(name: 'Fika'),
      Lga(name: 'Fune'),
      Lga(name: 'Gaidam'),
      Lga(name: 'Gujba'),
      Lga(name: 'Jakusko'),
      Lga(name: 'Karasuwa'),
      Lga(name: 'Machina'),
      Lga(name: 'Nangere'),
      Lga(name: 'Potiskum'),
      Lga(name: 'Tarmuwa'),
      Lga(name: 'Yunusari'),
      Lga(name: 'Yobe East'),
    ],
  ),
  StateModel(
    name: 'Zamfara',
    lgas: [
      Lga(name: 'Anka'),
      Lga(name: 'Bakura'),
      Lga(name: 'Birnin Magaji'),
      Lga(name: 'Bukkuyum'),
      Lga(name: 'Gummi'),
      Lga(name: 'Gusau'),
      Lga(name: 'Kaita'),
      Lga(name: 'Maradun'),
      Lga(name: 'Shinkafi'),
      Lga(name: 'Talata Mafara'),
      Lga(name: 'Tsafe'),
      Lga(name: 'Zamfara West'),
    ],
  ),
  StateModel(
    name: 'Abuja',
    lgas: [],
  ),
];
