// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cT8jFIGUrt9SkPjTjWXTUzI8e8Gahgk',
    appId: '1:170234334876:web:9eecff12d379dd0f6be759',
    messagingSenderId: '170234334876',
    projectId: 'card-pay-64324',
    authDomain: 'card-pay-64324.firebaseapp.com',
    storageBucket: 'card-pay-64324.firebasestorage.app',
    measurementId: 'G-LVL0YG376S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbRg8tqmcQot45GWVZyh-2Ci_yCN1Ln6U',
    appId: '1:170234334876:android:4d5ed499d78a3b526be759',
    messagingSenderId: '170234334876',
    projectId: 'card-pay-64324',
    storageBucket: 'card-pay-64324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-Ig6UenKRyGRBsmz3QNEey-xit7Nkuc',
    appId: '1:170234334876:ios:4c10e94d660ec3296be759',
    messagingSenderId: '170234334876',
    projectId: 'card-pay-64324',
    storageBucket: 'card-pay-64324.firebasestorage.app',
    iosBundleId: 'com.example.cashApp',
  );
}
